---
Organizations:
    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: hyperledger_data/crypto-config/ordererOrganizations/dams.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"
    - &cec
        Name: cecMSP
        ID: cecMSP
        MSPDir: hyperledger_data/crypto-config/peerOrganizations/cec.dams.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('cecMSP.admin', 'cecMSP.peer', 'cecMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('cecMSP.admin', 'cecMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('cecMSP.admin')"
        AnchorPeers:
            - Host: peer0.cec.dams.com
              Port: 7051
    - &ia3
        Name: ia3MSP
        ID: ia3MSP
        MSPDir: hyperledger_data/crypto-config/peerOrganizations/ia3.dams.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('ia3MSP.admin', 'ia3MSP.peer', 'ia3MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('ia3MSP.admin', 'ia3MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('ia3MSP.admin')"
        AnchorPeers:
            - Host: peer0.ia3.dams.com
              Port: 7151
    - &ic3
        Name: ic3MSP
        ID: ic3MSP
        MSPDir: hyperledger_data/crypto-config/peerOrganizations/ic3.dams.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('ic3MSP.admin', 'ic3MSP.peer', 'ic3MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('ic3MSP.admin', 'ic3MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('ic3MSP.admin')"
        AnchorPeers:
            - Host: peer0.ic3.dams.com
              Port: 7251
    - &gov
        Name: govMSP
        ID: govMSP
        MSPDir: hyperledger_data/crypto-config/peerOrganizations/gov.dams.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('govMSP.admin', 'govMSP.peer', 'govMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('govMSP.admin', 'govMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('govMSP.admin')"
        AnchorPeers:
            - Host: peer0.gov.dams.com
              Port: 7351
Capabilities:
    Channel: &ChannelCapabilities
        V1_4_3: true
        V1_3: false
        V1_1: false
    Orderer: &OrdererCapabilities
        V1_4_2: true
        V1_1: false
    Application: &ApplicationCapabilities
        V1_4_2: true
        V1_3: false
        V1_2: false
        V1_1: false

Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ApplicationCapabilities
Orderer: &OrdererDefaults
    OrdererType: solo
    Addresses:
        - orderer.dams.com:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Kafka:
        Brokers:
            - 127.0.0.1:9092
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"
Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities
Profiles:
    TwoOrgsOrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *cec
                    - *ia3
                    - *ic3
                    - *gov
    TwoOrgsChannel:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *cec
                - *ia3
                - *ic3
                - *gov
            Capabilities:
                <<: *ApplicationCapabilities
...
