NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca-ic3-dams-com-7054.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca-ic3-dams-com-7054.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/ca-ic3-dams-com-7054.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/ca-ic3-dams-com-7054.pem
    OrganizationalUnitIdentifier: orderer
