NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/peer0-cec-ca-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/peer0-cec-ca-cert.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/peer0-cec-cert.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/peer0-cec-cert.pem
    OrganizationalUnitIdentifier: orderer